version: "3.8"

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - PORT=5055
    volumes:
      - ./configs/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
    networks:
      - media_net

  # 1. The VPN Container (Gluetun)
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<private_key>
      - WIREGUARD_ADDRESSES=<address>
      - SERVER_COUNTRIES=<country>
    volumes:
      - ./configs/gluetun:/gluetun
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped 

  # 2. The qBittorrent Container (Standard)
  qbittorrent:
    image: linuxserver/qbittorrent:latest # Official ARM64 support
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Hungary/Budapest
      - WEBUI_PORT=8081
    ports:
      - "8081:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./configs/qbittorrent:/config
      - /Users/media/media/downloads:/downloads
      - /Users/media/media/tv:/tv
      - /Users/media/media/movies:/movies
    # Connect to the Gluetun network so all traffic goes through VPN
    network_mode: "container:gluetun"
    restart: unless-stopped
    depends_on:
      - gluetun

  jellyfin:
    image: ghcr.io/hotio/jellyfin:latest
    container_name: jellyfin 
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./configs/jellyfin:/config
      - /Users/media/media/tv:/tv
      - /Users/media/media/movies:/movies
      - /Users/media/media/downloads:/downloads
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - media_net

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Hungary/Budapest
    volumes:
      - ./configs/sonarr:/config
      - /Users/media/media/tv:/tv
      - /Users/media/media/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media_net

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Hungary/Budapest
    volumes:
      - ./configs/radarr:/config
      - /Users/media/media/movies:/movies
      - /Users/media/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media_net

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Hungary/Budapest
    volumes:
      - ./configs/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media_net

  bazarr:
    image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Hungary/Budapest
    volumes:
      - ./configs/bazarr:/config
      - /Users/media/media/tv:/tv
      - /Users/media/media/movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media_net

networks:
  media_net:
    driver: bridge
